-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.11.3.469
-- Module  Version: 5.7
-- Fri Feb 19 01:20:30 2021

-- parameterized module component declaration
component Pll125toclock
    port (CLK: in std_logic; CLKOP: out std_logic; CLKOK: out std_logic; 
        LOCK: out std_logic);
end component;

-- parameterized module component instance
__ : Pll125toclock
    port map (CLK=>__, CLKOP=>__, CLKOK=>__, LOCK=>__);
