/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.11.3.469 */
/* Module Version: 5.7 */
/* Sun Jan 24 16:49:42 2021 */

/* parameterized module instance */
my_pll __ (.CLK( ), .CLKOP( ), .CLKOK( ), .LOCK( ));
